# Generated by Django 5.2.17 on 2026-08-14 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('comum', '0002_carga_inicial_dominio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=80, verbose_name='nome')),
                ('valida', models.BooleanField(default=True, help_text='Falso para rascunho com choque (RN02).', verbose_name='válida')),
                ('preferida', models.BooleanField(default=False, verbose_name='preferida')),
                ('token_publico', models.UUIDField(blank=True, help_text='Token do link somente-leitura (RF40).', null=True, unique=True, verbose_name='token público')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='catalogo.semestre', verbose_name='semestre')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'grade',
                'verbose_name_plural': 'grades',
                'db_table': 'grade',
                'ordering': ['-atualizado_em'],
            },
        ),
        migrations.CreateModel(
            name='GradeTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridade', models.CharField(choices=[('PRINCIPAL', 'Principal'), ('ALTERNATIVA', 'Alternativa')], default='PRINCIPAL', help_text='Classificação da turma no cenário (RF29).', max_length=12, verbose_name='prioridade')),
                ('choque_reconhecido', models.BooleanField(default=False, help_text='Permite gravar a grade mesmo com choque (RF23).', verbose_name='choque reconhecido pelo discente')),
                ('adicionado_em', models.DateTimeField(auto_now_add=True, verbose_name='adicionado em')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='planejamento.grade', verbose_name='grade')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_de_grade', to='catalogo.turma', verbose_name='turma')),
            ],
            options={
                'verbose_name': 'turma da grade',
                'verbose_name_plural': 'turmas da grade',
                'db_table': 'grade_turma',
                'ordering': ['turma__componente__codigo'],
            },
        ),
        migrations.CreateModel(
            name='RestricaoDisponibilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(blank=True, max_length=120, verbose_name='motivo')),
                ('codigo_dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restricoes', to='comum.codigodia', verbose_name='dia da semana')),
                ('codigo_horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restricoes', to='comum.codigohorario', verbose_name='bloco de horário')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restricoes', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'restrição de disponibilidade',
                'verbose_name_plural': 'restrições de disponibilidade',
                'db_table': 'restricao_disponibilidade',
                'ordering': ['codigo_dia__ordem', 'codigo_horario__ordem'],
            },
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(fields=('usuario', 'semestre', 'nome'), name='grade_nome_unico_por_semestre'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(condition=models.Q(('preferida', True)), fields=('usuario', 'semestre'), name='grade_preferida_unica_por_semestre'),
        ),
        migrations.AddConstraint(
            model_name='gradeturma',
            constraint=models.UniqueConstraint(fields=('grade', 'turma'), name='grade_turma_unica'),
        ),
        migrations.AddConstraint(
            model_name='restricaodisponibilidade',
            constraint=models.UniqueConstraint(fields=('usuario', 'codigo_dia', 'codigo_horario'), name='restricao_disponibilidade_unica'),
        ),
    ]
