# Generated by Django 5.2.17 on 2026-08-14 17:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilDiscente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('periodo_ingresso', models.CharField(blank=True, help_text='Semestre no formato AAAAP.', max_length=6, verbose_name='período de ingresso')),
                ('media_creditos_por_periodo', models.SmallIntegerField(blank=True, help_text='Usada na projeção de períodos restantes (RF20).', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(40)], verbose_name='média de créditos por período')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('matriz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfis', to='catalogo.matrizcurricular', verbose_name='matriz curricular')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'perfil do discente',
                'verbose_name_plural': 'perfis dos discentes',
                'db_table': 'perfil_discente',
            },
        ),
        migrations.CreateModel(
            name='ProgressoComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CURSADO', 'Cursado'), ('EM_CURSO', 'Em curso'), ('PENDENTE', 'Pendente')], default='PENDENTE', max_length=12, verbose_name='situação')),
                ('natureza', models.CharField(choices=[('MATRIZ', 'Consta da matriz'), ('OPTATIVO', 'Optativo fora da matriz'), ('MODULO_LIVRE', 'Módulo livre')], default='MATRIZ', help_text='Classificação de componentes fora da matriz (RF17).', max_length=15, verbose_name='natureza')),
                ('por_equivalencia', models.BooleanField(default=False, help_text='Cumprimento por componente equivalente (RF19).', verbose_name='cumprido por equivalência')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressos', to='catalogo.componentecurricular', verbose_name='componente')),
                ('componente_equivalente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equivalencias_aproveitadas', to='catalogo.componentecurricular', verbose_name='componente equivalente aproveitado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresso', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'progresso em componente',
                'verbose_name_plural': 'progressos em componentes',
                'db_table': 'progresso_componente',
                'ordering': ['componente__codigo'],
                'indexes': [models.Index(fields=['usuario', 'status'], name='progresso_usuario_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'componente'), name='progresso_componente_unico')],
            },
        ),
    ]
