# Generated by Django 5.2.17 on 2026-08-14 17:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comum', '0002_carga_inicial_dominio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('nome', models.CharField(max_length=200, unique=True, verbose_name='nome')),
            ],
            options={
                'verbose_name': 'docente',
                'verbose_name_plural': 'docentes',
                'db_table': 'docente',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ComponenteCurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('codigo', models.CharField(max_length=15, unique=True, verbose_name='código')),
                ('nome', models.CharField(max_length=200, verbose_name='nome')),
                ('carga_horaria', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='carga horária')),
                ('departamento', models.CharField(blank=True, max_length=120, verbose_name='departamento')),
                ('ementa', models.TextField(blank=True, verbose_name='ementa')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'componente curricular',
                'verbose_name_plural': 'componentes curriculares',
                'db_table': 'componente_curricular',
                'ordering': ['codigo'],
                'indexes': [models.Index(fields=['nome'], name='componente_nome_idx'), models.Index(fields=['departamento'], name='componente_departamento_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('carga_horaria__gte', 0), ('carga_horaria__isnull', True), _connector='OR'), name='componente_carga_horaria_nao_negativa')],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('nome', models.CharField(max_length=160, verbose_name='nome')),
                ('codigo', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='código')),
                ('turno', models.CharField(blank=True, choices=[('DIURNO', 'Diurno'), ('NOTURNO', 'Noturno'), ('INTEGRAL', 'Integral')], max_length=20, verbose_name='turno')),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos', to='comum.campus', verbose_name='campus')),
            ],
            options={
                'verbose_name': 'curso',
                'verbose_name_plural': 'cursos',
                'db_table': 'curso',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='MatrizCurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('nome', models.CharField(max_length=160, verbose_name='nome')),
                ('codigo', models.CharField(blank=True, max_length=20, verbose_name='código')),
                ('vigencia_inicio', models.CharField(blank=True, help_text='Semestre no formato AAAAP.', max_length=6, verbose_name='início de vigência')),
                ('vigencia_fim', models.CharField(blank=True, help_text='Vazio quando a matriz está vigente.', max_length=6, verbose_name='fim de vigência')),
                ('carga_horaria_minima_periodo_letivo', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='carga horária mínima por período')),
                ('carga_horaria_maxima_periodo_letivo', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='carga horária máxima por período')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matrizes', to='catalogo.curso', verbose_name='curso')),
            ],
            options={
                'verbose_name': 'matriz curricular',
                'verbose_name_plural': 'matrizes curriculares',
                'db_table': 'matriz_curricular',
                'ordering': ['curso__nome', '-vigencia_inicio'],
            },
        ),
        migrations.CreateModel(
            name='MatrizComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_recomendado', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='período recomendado')),
                ('natureza', models.CharField(choices=[('OBRIGATORIO', 'Obrigatório'), ('OPTATIVO', 'Optativo'), ('MODULO_LIVRE', 'Módulo livre')], default='OBRIGATORIO', max_length=15, verbose_name='natureza')),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matrizes', to='catalogo.componentecurricular', verbose_name='componente')),
                ('matriz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='catalogo.matrizcurricular', verbose_name='matriz')),
            ],
            options={
                'verbose_name': 'componente da matriz',
                'verbose_name_plural': 'componentes da matriz',
                'db_table': 'matriz_componente',
                'ordering': ['periodo_recomendado', 'componente__codigo'],
            },
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Formato AAAAP (ex.: 20262).', max_length=6, unique=True, verbose_name='código')),
                ('ano', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(2000)], verbose_name='ano')),
                ('periodo', models.SmallIntegerField(choices=[(0, 'Verão'), (1, '1º período'), (2, '2º período')], verbose_name='período')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='início das aulas')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='fim das aulas')),
                ('ativo', models.BooleanField(default=False, verbose_name='ativo')),
                ('oferta_atualizada_em', models.DateTimeField(blank=True, help_text='Data da última carga de oferta (RF12, RF45).', null=True, verbose_name='oferta atualizada em')),
            ],
            options={
                'verbose_name': 'semestre',
                'verbose_name_plural': 'semestres',
                'db_table': 'semestre',
                'ordering': ['-ano', '-periodo'],
                'constraints': [models.UniqueConstraint(fields=('ano', 'periodo'), name='semestre_unico'), models.CheckConstraint(condition=models.Q(('ano__gte', 2000)), name='semestre_ano_valido'), models.CheckConstraint(condition=models.Q(('periodo__in', [0, 1, 2])), name='semestre_periodo_valido')],
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, verbose_name='código')),
                ('vagas_ofertadas', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='vagas ofertadas')),
                ('vagas_ocupadas', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='vagas ocupadas')),
                ('modalidade', models.CharField(blank=True, choices=[('PRESENCIAL', 'Presencial'), ('REMOTA', 'Remota'), ('HIBRIDA', 'Híbrida')], max_length=20, verbose_name='modalidade')),
                ('observacao', models.TextField(blank=True, verbose_name='observação')),
                ('coletado_em', models.DateTimeField(blank=True, help_text='Data da coleta dos dados desta turma (RF45).', null=True, verbose_name='coletado em')),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='catalogo.componentecurricular', verbose_name='componente')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='catalogo.semestre', verbose_name='semestre')),
            ],
            options={
                'verbose_name': 'turma',
                'verbose_name_plural': 'turmas',
                'db_table': 'turma',
                'ordering': ['componente__codigo', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='TurmaDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adicionado_em', models.DateTimeField(auto_now_add=True, verbose_name='adicionado em')),
                ('docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vinculos_turma', to='catalogo.docente', verbose_name='docente')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_docente', to='catalogo.turma', verbose_name='turma')),
            ],
            options={
                'verbose_name': 'docente da turma',
                'verbose_name_plural': 'docentes da turma',
                'db_table': 'turma_docente',
            },
        ),
        migrations.AddField(
            model_name='turma',
            name='docentes',
            field=models.ManyToManyField(blank=True, related_name='turmas', through='catalogo.TurmaDocente', to='catalogo.docente', verbose_name='docentes'),
        ),
        migrations.CreateModel(
            name='TurmaHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(blank=True, max_length=40, verbose_name='local')),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horarios', to='comum.campus', verbose_name='campus')),
                ('codigo_dia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='horarios', to='comum.codigodia', verbose_name='dia da semana')),
                ('codigo_horario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='horarios', to='comum.codigohorario', verbose_name='bloco de horário')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='catalogo.turma', verbose_name='turma')),
            ],
            options={
                'verbose_name': 'horário da turma',
                'verbose_name_plural': 'horários da turma',
                'db_table': 'turma_horario',
                'ordering': ['codigo_dia__ordem', 'codigo_horario__ordem'],
            },
        ),
        migrations.CreateModel(
            name='ComponenteRelacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PRE_REQUISITO', 'Pré-requisito'), ('CO_REQUISITO', 'Co-requisito'), ('EQUIVALENCIA', 'Equivalência')], max_length=15, verbose_name='tipo')),
                ('grupo', models.SmallIntegerField(default=1, help_text='Relações do mesmo grupo combinam-se por OU.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='grupo')),
                ('bidirecional', models.BooleanField(default=False, help_text='Aplicável a equivalências (RN06).', verbose_name='bidirecional')),
                ('observacao', models.TextField(blank=True, verbose_name='observação')),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relacoes', to='catalogo.componentecurricular', verbose_name='componente')),
                ('componente_relacionado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relacoes_inversas', to='catalogo.componentecurricular', verbose_name='componente relacionado')),
            ],
            options={
                'verbose_name': 'relação entre componentes',
                'verbose_name_plural': 'relações entre componentes',
                'db_table': 'componente_relacao',
                'ordering': ['componente__codigo', 'tipo', 'grupo'],
                'constraints': [models.UniqueConstraint(fields=('componente', 'componente_relacionado', 'tipo'), name='componente_relacao_unica'), models.CheckConstraint(condition=models.Q(('componente', models.F('componente_relacionado')), _negated=True), name='componente_relacao_sem_auto_referencia')],
            },
        ),
        migrations.AddConstraint(
            model_name='matrizcurricular',
            constraint=models.UniqueConstraint(fields=('curso', 'nome'), name='matriz_curricular_unica_por_curso'),
        ),
        migrations.AddConstraint(
            model_name='matrizcurricular',
            constraint=models.CheckConstraint(condition=models.Q(('carga_horaria_minima_periodo_letivo__gte', 0), ('carga_horaria_minima_periodo_letivo__isnull', True), _connector='OR'), name='matriz_curricular_ch_minima_nao_negativa'),
        ),
        migrations.AddConstraint(
            model_name='matrizcurricular',
            constraint=models.CheckConstraint(condition=models.Q(('carga_horaria_maxima_periodo_letivo__gte', 0), ('carga_horaria_maxima_periodo_letivo__isnull', True), _connector='OR'), name='matriz_curricular_ch_maxima_nao_negativa'),
        ),
        migrations.AddConstraint(
            model_name='matrizcomponente',
            constraint=models.UniqueConstraint(fields=('matriz', 'componente'), name='matriz_componente_unico'),
        ),
        migrations.AddConstraint(
            model_name='matrizcomponente',
            constraint=models.CheckConstraint(condition=models.Q(('periodo_recomendado__range', (1, 20)), ('periodo_recomendado__isnull', True), _connector='OR'), name='matriz_componente_periodo_valido'),
        ),
        migrations.AddConstraint(
            model_name='turmadocente',
            constraint=models.UniqueConstraint(fields=('turma', 'docente'), name='turma_docente_unico'),
        ),
        migrations.AddConstraint(
            model_name='turma',
            constraint=models.UniqueConstraint(fields=('semestre', 'componente', 'codigo'), name='turma_unica_no_semestre'),
        ),
        migrations.AddConstraint(
            model_name='turma',
            constraint=models.CheckConstraint(condition=models.Q(('vagas_ofertadas__gte', 0), ('vagas_ofertadas__isnull', True), _connector='OR'), name='turma_vagas_ofertadas_nao_negativas'),
        ),
        migrations.AddConstraint(
            model_name='turma',
            constraint=models.CheckConstraint(condition=models.Q(('vagas_ocupadas__gte', 0), ('vagas_ocupadas__isnull', True), _connector='OR'), name='turma_vagas_ocupadas_nao_negativas'),
        ),
        migrations.AddIndex(
            model_name='turmahorario',
            index=models.Index(fields=['codigo_dia', 'codigo_horario'], name='turma_horario_slot_idx'),
        ),
        migrations.AddConstraint(
            model_name='turmahorario',
            constraint=models.UniqueConstraint(fields=('turma', 'codigo_dia', 'codigo_horario'), name='turma_horario_unico'),
        ),
    ]
