# Generated by Django 5.2.17 on 2026-08-14 17:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='código')),
                ('nome', models.CharField(max_length=120, verbose_name='nome')),
            ],
            options={
                'verbose_name': 'campus',
                'verbose_name_plural': 'campi',
                'db_table': 'campus',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='CodigoDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('codigo', models.CharField(max_length=2, unique=True, verbose_name='código')),
                ('dia_da_semana', models.CharField(max_length=20, verbose_name='dia da semana')),
                ('ordem', models.SmallIntegerField(unique=True, verbose_name='ordem')),
            ],
            options={
                'verbose_name': 'código de dia',
                'verbose_name_plural': 'códigos de dia',
                'db_table': 'codigo_dia',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='CodigoHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('codigo', models.CharField(max_length=4, unique=True, verbose_name='código')),
                ('horario', models.CharField(max_length=20, verbose_name='horário')),
                ('hora_inicio', models.TimeField(verbose_name='hora de início')),
                ('hora_fim', models.TimeField(verbose_name='hora de término')),
                ('turno', models.CharField(choices=[('M', 'Matutino'), ('T', 'Vespertino'), ('N', 'Noturno')], max_length=1, verbose_name='turno')),
                ('ordem', models.SmallIntegerField(unique=True, verbose_name='ordem')),
            ],
            options={
                'verbose_name': 'código de horário',
                'verbose_name_plural': 'códigos de horário',
                'db_table': 'codigo_horario',
                'ordering': ['ordem'],
                'constraints': [models.CheckConstraint(condition=models.Q(('hora_inicio__lt', models.F('hora_fim'))), name='codigo_horario_inicio_antes_do_fim')],
            },
        ),
        migrations.CreateModel(
            name='RegistroCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('origem', models.CharField(choices=[('CSV', 'Importação de arquivo'), ('MANUAL', 'Edição manual'), ('MIGRACAO', 'Migração de dados')], default='CSV', max_length=10, verbose_name='origem')),
                ('entidade', models.CharField(max_length=60, verbose_name='entidade afetada')),
                ('registros_afetados', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='registros afetados')),
                ('detalhe', models.TextField(blank=True, verbose_name='detalhe')),
                ('curador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargas', to=settings.AUTH_USER_MODEL, verbose_name='curador')),
            ],
            options={
                'verbose_name': 'registro de carga',
                'verbose_name_plural': 'registros de carga',
                'db_table': 'registro_carga',
                'ordering': ['-criado_em'],
            },
        ),
    ]
